<?php echo $this->doctype(); ?>
<html lang="zh-cn">
<head>
<meta charset="utf-8">
<?php 
echo $this->headTitle($this->translate('ICC品牌云'))->setSeparator(' - ')->setAutoEscape(false);
echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
echo $this->headLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $this->basePath() . '/img/favicon.ico'
))->prependStylesheet($this->basePath() . '/js/extjs/4.2.1/resources/css/ext-all-neptune.css');
echo $this->headScript()->prependFile($this->basePath().'/js/extjs/4.2.1/bootstrap.js');
?>
</head>
<body>
	<div class="header"></div>
	<div class="container"><?php echo $this->content; ?></div>
	<footer>
		<p>&copy; 2011 - <?php echo date('Y') ?> by iCatholic Cloud BP Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
	</footer>
</body>
</html>