<?php echo $this->doctype(); ?>
<html lang="zh-cn">
<head>
<meta charset="utf-8">
<?php
echo $this->headTitle($this->translate('ICC品牌云平台'))
    ->setSeparator(' - ')
    ->setAutoEscape(false);
echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
echo $this->headLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $this->basePath() . '/img/favicon.ico'
))
    ->appendStylesheet($this->basePath() . '/css/ext-theme-neptune-all.css')
    ->appendStylesheet($this->basePath() . '/css/icon.css');
echo $this->headScript()
    ->appendFile($this->basePath() . '/js/build/production/icc/app.js')
    ->appendFile($this->basePath() . '/js/resources/common.js');

?>
</head>
<body>
<?php echo $this->content; ?>
</body>
</html>