<?php echo $this->doctype(); ?>
<html lang="zh-cn">
<head>
<meta charset="utf-8">
<?php
echo $this->headTitle($this->translate('ICC品牌云 -- iCatholic Brand Cloud Platform'))
    ->setSeparator(' - ')
    ->setAutoEscape(false);
echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
echo $this->headLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $this->basePath() . '/img/favicon.ico'
))
    ->appendStylesheet($this->basePath() . '/js/build/production/icc/resources/icc-all.css');
echo $this->headScript()->appendFile($this->basePath() . '/js/build/production/icc/app.js');
?>
</head>
<body>
</body>
</html>